Добавлен scheduler.
karoziya/TeamRotationActivity pull request #25
Opened 2023-11-23 20:06 UTC by Jenausmax

Добавлен scheduler. На основе библиотеки https://www.hangfire.io/
Для хранилища шедулера использована библиотека InMemory.

Создан отдельный сервис RegistrationJobService для регистрации и запуска механизма шедулера.

Выделен интерфейс отдельной джобы IJob. Класс имплементирующий этот интерфейс представляет собой выполняемую работу. 
Джобы регистрируются в DI в классе JobsServiceExtensions

Создана джоба для регистрации мессадж джоб, которая будет подниматься каждый будний день в 6 утра и создавать нужные мессадж джобы на этот день.

2023-11-24 04:10 UTC, karoziya commented on TeamRotationActivity.Models/Models/ActivityWork.cs
> +    public Guid MemberId { get; set; }
А это зачем? почему не взять первого в списке? смотрю в data2.json там активный ведущий тот, которого нет в списке, придется еще потом и проверку добавлять чтоб не было расхождения

2023-11-24 04:41 UTC, karoziya requested changes
я не закончил ревью, есть у меня вопросы, но пока так.

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Models/Models/ActivityWork.cs
> +    public Guid MemberId { get; set; }
А это зачем? почему не взять первого в списке? смотрю в data2.json там активный ведущий тот, которого нет в списке, придется еще потом и проверку добавлять чтоб не было расхождения

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Models/Interfaces/Services/IActivitySaverService.cs
> +    public ActivityWork CreateActivities();
я не то бы ратую за коментарии, но тут как-то выдяелтся, либо везде сделать либо везде удалить.

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +    private readonly IActivitySaverService _activitySaverService;
блин тут код по стандартам MS а не по стандартам Directum, надо везде однобразно, я за Dir, но обсуждаемо.

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        if (activities == null)
проверку надо явно сделать аньше создания activitiesUpdate ибо зачем его создавать.

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +                if (activity.ActivityPeriod == ActivityPeriod.EveryDay)
тут намерено только для одного периода? кажется что не сложно сделать обработку сразу всех доступных

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/Interfaces/IJob.cs
> +/// Интерфейс фоновой службы.
интерфейс фоновой службы, но класс джобы?

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageJob.cs
> +    public void ExecuteAsync(string jobId, string message)
почему async?

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Core/Services/RegistrationJobService.cs
> +        manager.AddOrUpdate<IJob<MessageSchedulerJob>>(jobId, pr => pr.ExecuteAsync(jobId, CancellationToken.None), "0 6 * * 1-5");
кто-то говорил что не любит крон :)

2023-11-24 04:41 UTC, karoziya commented on TeamRotationActivity.Core/Services/RegistrationJobService.cs
> +        manager.AddOrUpdate<IJob<MessageSchedulerJob>>(jobId, pr => pr.ExecuteAsync(jobId, CancellationToken.None), "0 6 * * 1-5");
предлагаю не ограничивать буднями, пусть работает всегда, денег ведь не просит

2023-11-25 17:38 UTC, karoziya submitted a review, later dismissed
Я еще не все понял, пусть будет так ;)

2023-11-25 17:38 UTC, karoziya commented on TeamRotationActivity.Models/Interfaces/Services/ISaverService.cs
> +public interface ISaverService
Почему сохранения если он еще и загружает?

2023-11-26 13:13 UTC, karoziya commented on TeamRotationActivity.Core/Services/RegistrationJobService.cs
> +        if (DateTime.Now.Hour >= 6 && DateTime.Now.Hour < 18)
Ну е мае, договаорились же так не делать

2023-11-26 13:35 UTC, karoziya commented
Сама идея с ханфаером и джобами стартующими на текущй день мне нравится. Но реализация страшная.
У нас на две модели ДВЕ КРАЛ!!! уже 5 сервисо, еще есть расширения, билдеры  я не могу это прянть, а эти волшебные константы 6,18 ну это же smell, ну вонят просто.

Зачем  у нас общий предок у активности и пользователя?   у них вообще нет ничего общего если смотреть именно реалии мира да у них есть ИД но нафига объеденять? возможно это паттерн такой ткни пжл  ссылкой, часто я бываю не прав.

Пошле думать

2023-11-26 14:05 UTC, karoziya commented
Короче пока предлагаю выкинуть rotationsevice совсем, сначала давай доведем до ума джобу по сообщениям потом будем дальше, ты сам сказал что очень много кода.

RegistrationJobService сервис регистарции джобов, почему там не реализовать всю логику по джобам? зачем нам еще IJobBuilder. Предлагаю убрать. Когда стартуем задачи, лигика следущая:
Запускаем все Recurring джобы немедленно
 и ставим их в очередь в 00:00 каждый день, тогда у нас не будет лага по времени и не будет никакого триггера.

Не должен у нас метод постановки джобы в работу знать ньюансы реализации что это за джоба, он просто пихает туда абстрактную джобу чтоб она выполнилась в данное время. 
MessageSchedulerJob должен в работу ставить MessageJob и именно MessageJob должен владеть сообщением. 
Думаю пока этого хватит, Могу сам все это сделать.

2023-11-26 14:23 UTC, Jenausmax commented on TeamRotationActivity.Core/Services/RegistrationJobService.cs
> +        if (DateTime.Now.Hour >= 6 && DateTime.Now.Hour < 18)
ну тут мой косяк) точнеее просто сделан триггер на коленке.

2023-11-26 14:28 UTC, Jenausmax commented
`RegistrationJobService` так у нас и не знает как реализуются джобы...это как раз и позволяет сделать `IJobBuilder`. `RegistrationJobService` просто берет и запускает 2 повторяющиеся джобы и все....

2023-11-26 17:34 UTC, karoziya commented
> Хмм... "Не должен у нас метод постановки джобы в работу знать ньюансы реализации что это за джоба, он просто пихает туда абстрактную джобу чтоб она выполнилась в данное время." интересно конечно. возможно не секу в паттернах(( как понять что именно нужно запустить? Если мы запустим абстракцию IJob, то не понятно какой сервис будет выдернут из DI. нужно тогда запускать IJob.
> 
> Сервис поэтому и называется Registration.
> 
> Я пока не понимаю как это реализовать...

Я тут попытался накидать и понял что не понимаю как работает этот ханфаер, да так не работает как я хотел, надо обсудить

2023-11-26 18:01 UTC, Jenausmax commented
> > Хмм... "Не должен у нас метод постановки джобы в работу знать ньюансы реализации что это за джоба, он просто пихает туда абстрактную джобу чтоб она выполнилась в данное время." интересно конечно. возможно не секу в паттернах(( как понять что именно нужно запустить? Если мы запустим абстракцию IJob, то не понятно какой сервис будет выдернут из DI. нужно тогда запускать IJob.
> > Сервис поэтому и называется Registration.
> > Я пока не понимаю как это реализовать...
> 
> Я тут попытался накидать и понял что не понимаю как работает этот ханфаер, да так не работает как я хотел, надо обсудить

Значит надо обсудить..

2023-11-30 17:49 UTC, karoziya requested changes

2023-11-30 17:49 UTC, karoziya commented on TeamRotationActivity.Core/Builders/JobBuilder.cs
> +    public void Trigger(string jobId)
зачем нам триггер? просто ставь джобу в очередь с 0 секунд либо через Enqueue

2023-11-30 17:49 UTC, karoziya commented on TeamRotationActivity.Core/Services/RegistrationJobService.cs
> +        var messageRecurringJobId = Guid.NewGuid().ToString();
А зачем гуид? давай дадим нормальное название, чтоб выидно было чего у нас там в очереди

2023-11-30 17:49 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +    public async Task ExecuteAsync(string jobId, CancellationToken token = default)
Не понимаю где используется jobId, если не используется давай уберем

2023-11-30 17:49 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +    public MessageSchedulerJob(IReadWriteService activitySaverService, IActivityService activityService, IJobBuilder builder)
имя интерфейса и переменной которая его олецитворяет совсем не коррелируют, IReadWriteService activitySaverService

2023-11-30 17:49 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        await _activitySaverService.SaveActivitiesAsync(updateActivities);
тут ерунда какая-то, если у нас 3 активности, а обновляем только одну, то остальные две сотрем в итоге.
Хочется чего-то такого, разбить по методам для найденной активности:
```
Отправить сообщение
Обновить поля
Сохранить активность
```
И не надо хранить эти активности, отработали активность и забыли

2023-11-30 18:20 UTC, Jenausmax commented on TeamRotationActivity.Core/Builders/JobBuilder.cs
> +    public void Trigger(string jobId)
Триггер нужен для того, чтобы после запуска программы джобы отработали сразу.  Enqueue ставит джобу в очередь и заставляет джобу сработать сразу, но она  больше не повторяется.

2023-11-30 19:28 UTC, Jenausmax commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        await _activitySaverService.SaveActivitiesAsync(updateActivities);
Мы пока не можем сохранять отдельно активность. только массивом. Так устроен наш сервис ReadWriteService.  И сейчас алгоритм такой:
- Берем активность из массива
- актуализируем дату активности (если дата просрочена)
- Создаем джобу по отправке сообщения если дата подошла
- Обновляем нужные поля, если надо
- Сохраняем активность в массив updateActivities
- Повторяем алгоритм если активности еще есть
- Сохраняем все активности в файлик.

Предлагаю пока оставить так.
Создать таску по добавлению методов по поиску по ид и сохранению отдельной сущности в ReadWriteService.

А потом переписать работу с активностью по алгоритму  "отработали активность и забыли"
-Отправить сообщение
-Обновить поля
-Сохранить активность

2023-11-30 19:36 UTC, Jenausmax commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +    public MessageSchedulerJob(IReadWriteService activitySaverService, IActivityService activityService, IJobBuilder builder)
Исправлено.

2023-11-30 19:36 UTC, Jenausmax commented on TeamRotationActivity.Core/Services/RegistrationJobService.cs
> +        var messageRecurringJobId = Guid.NewGuid().ToString();
Исправлено.

2023-11-30 19:37 UTC, Jenausmax commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +    public async Task ExecuteAsync(string jobId, CancellationToken token = default)
Убрал.

2023-11-30 19:39 UTC, Jenausmax commented on TeamRotationActivity.Core/Builders/JobBuilder.cs
> +    public void Trigger(string jobId)
т.е если использовать Enqueue, то нужно будет добавлять метод по работе с Enqueue в `JobBuilder`.

2023-11-30 20:11 UTC, Jenausmax commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        await _activitySaverService.SaveActivitiesAsync(updateActivities);
Не сотрем. Все активности пройдут через апдейт и сохранятся. Сделано для актуализации даты(т.е. если дата просрочена).

2023-12-01 04:18 UTC, karoziya requested changes

2023-12-01 04:18 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        if (activities == null)
Это выражение смысла не имеет

2023-12-01 04:18 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        var activities = await _activitySaverService.LoadActivitiesFromFileAsync();
Как раз на КК обсуждали, тут прям выперлись нюансы реализации знания про файл и т.п. Для чего нам не скрыть сохранялку за activityService'ом. Я просто говорю activityService.GetEntities и он уже сам знает откуда загрузить.

2023-12-01 04:18 UTC, karoziya commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        await _activitySaverService.SaveActivitiesAsync(updateActivities);
Да точно все туда добавляются, не досмотрел. Но и сейчас код выглядит странно сначала получаем actualizeActivity а потом еще и activityUpdate через CalculateActivityDate при этом по сути тут операции с одной только активностью и почему-то один метод локальный, другой через сервис, скорее должно быть где-то в одном месте.
Кажется что если у нас будет сохранние активности по одной через сервис, то это будет прозрачнее и дальше нам будет намного проще когда будет страница редактирования активности, там нам тоже надо будет сохранять по одной.

2023-12-02 17:08 UTC, Jenausmax commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        if (activities == null)
Убрал.

2023-12-02 17:22 UTC, Jenausmax commented on TeamRotationActivity.Jobs/Jobs/MessageSchedulerJob.cs
> +        var activities = await _activitySaverService.LoadActivitiesFromFileAsync();
Обсуждено. Делаем в другой таске.

2023-12-07 05:12 UTC, karoziya approved these changes

2023-12-11 11:19 UTC, merged